//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Matriculacion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatriculacionEntities : DbContext
    {
        public MatriculacionEntities()
            : base("name=MatriculacionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<Cuatrimestre> Cuatrimestres { get; set; }
        public virtual DbSet<Cursando> Cursandoes { get; set; }
        public virtual DbSet<Imparte> Impartes { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Estudiante> Estudiantes { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
    }
}
